[default]
SERVER_RELOAD = 1
PROXY_ROOT_PATH = ""
API_PREFIX = ""
ENABLE_CORS = 1
LLM_MODEL = "gemini-2.0-flash"
#LLM_MODEL = "gemini-2.5-pro"
LLM_SERVICE_TIMEOUT = 60


[production]
API_URL_BASE = "https://prodution-host.com/"


[development]
API_URL_BASE = "http://localhost:8000/"


[testing]
API_URL_BASE = "http://localhost:8000/"