[default]
SERVER_RELOAD = 1
PROXY_ROOT_PATH = ""
API_PREFIX = ""
ENABLE_CORS = 1
CORS_ORIGINS = ["*"]
LLM_MODEL = "gpt-4o"
LLM_SERVICE_TIMEOUT = 60
MONGO_DATABASE = "basiquinho"
MONGO_COLLECTION_STATE = "state"


[production]
API_URL_BASE = "https://prodution-host.com/"


[development]
API_URL_BASE = "http://localhost:8000/"


[testing]
API_URL_BASE = "http://localhost:8000/"