[default]
SERVER_RELOAD = true
PROXY_ROOT_PATH = ""
API_PREFIX = ""
ENABLE_CORS = true
CORS_ORIGINS = ["*"]
LLM_MODEL = "gpt-5-mini"
LLM_SERVICE_TIMEOUT = 60
SQLITE_PATH = "checkpoints.sqlite"


[production]



[development]



[testing]
